version: '3.8'

services:
  sql1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql1
    user: root
    ports:
      - "14331:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123!
      - MSSQL_AGENT_ENABLED=True
    volumes:
      - ./volumes/sql1/data:/var/opt/mssql/data
      - ./shared/backup:/var/opt/mssql/backup

  sql2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql2
    user: root
    ports:
      - "14332:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123!
      - MSSQL_AGENT_ENABLED=True
    volumes:
      - ./volumes/sql2/data:/var/opt/mssql/data
      - ./shared/backup:/var/opt/mssql/backup

  sql3:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql3
    user: root
    ports:
      - "14333:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123!
      - MSSQL_AGENT_ENABLED=True
    volumes:
      - ./volumes/sql3/data:/var/opt/mssql/data
      - ./shared/backup:/var/opt/mssql/backup

networks:
  default:
    name: mssql-network
